/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lector_dom;

import java.io.File;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import org.w3c.dom.*;

/**
 *
 * @author Pablo Martin
 */
public class Interfaz extends javax.swing.JFrame {

    Lector_DOM gesDOM = new Lector_DOM();
    ManejadorSAX gesSAX = new ManejadorSAX();
    JAXB gesJAXB = new JAXB();
    public static File fileXML = new File("Personas.xml");

    /**
     * Creates new form Interfaz
     */
    private File dialogoSeleccionarFichero() {
        //este metodo hace que se muestre el menu para seleccionar el archivo
        File fichero = null;

        JFileChooser fc = new JFileChooser();
        fc.setMultiSelectionEnabled(false);
        fc.setDialogType(JFileChooser.OPEN_DIALOG);
        int rv = fc.showOpenDialog(this);
        if (rv == JFileChooser.APPROVE_OPTION) {
            fichero = fc.getSelectedFile();
        }
        return fichero;
    }
    Gestionar_xpath gesXpath = new Gestionar_xpath();

    private File dialogoSeleccionTipoRecurso() {
        //este metodo hace que se muestre el menu para seleccionar el archivo
        File fichero = null;

        JFileChooser fc = new JFileChooser();
        fc.setMultiSelectionEnabled(false);
        fc.setDialogType(JFileChooser.OPEN_DIALOG);
        int rv = fc.showOpenDialog(this);
        if (rv == JFileChooser.APPROVE_OPTION) {
            fichero = fc.getSelectedFile();
        }
        return fichero;
    }

    public Interfaz() {
        this.gesJAXB = new JAXB();
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        mostrarDOM = new javax.swing.JButton();
        mensaje = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        nombre = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        apellido1 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        apellido2 = new javax.swing.JTextField();
        botonAñadido1 = new javax.swing.JButton();
        Guardar = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        nombrePersona = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        newElement = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        mostrarSAX = new javax.swing.JButton();
        mostrarJAXB = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        sexo = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        nacimiento = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        edad = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        dni = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        ciudad = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        nacionalidad = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        telefono = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        oldElement = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        salidaConsulta = new javax.swing.JTextArea();
        consulta1 = new javax.swing.JButton();
        consulta2 = new javax.swing.JButton();
        consulta3 = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        consulta = new javax.swing.JTextArea();
        consulta4 = new javax.swing.JButton();
        consulta5 = new javax.swing.JButton();
        consulta6 = new javax.swing.JButton();
        consulta7 = new javax.swing.JButton();
        ejecutar = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        mensaje1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        mostrarDOM.setText("Mostrar contenido DOM");
        mostrarDOM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mostrarDOMActionPerformed(evt);
            }
        });

        mensaje.setText("<Fichero XML no encontrado>");

        jLabel1.setText("Nombre");

        jLabel2.setText("Apellido1");

        jLabel3.setText("Apellido2");

        botonAñadido1.setText("Añadir persona");
        botonAñadido1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonAñadido1ActionPerformed(evt);
            }
        });

        Guardar.setText("Guardar DOM como salida XML");
        Guardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GuardarActionPerformed(evt);
            }
        });

        jLabel4.setText("Nombre de la persona:");

        jLabel5.setText("Elemento nuevo:");

        jButton1.setText("Modificar persona");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        mostrarSAX.setText("Mostrar contenido SAX");
        mostrarSAX.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mostrarSAXActionPerformed(evt);
            }
        });

        mostrarJAXB.setText("Mostrar contenido JAXB");
        mostrarJAXB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mostrarJAXBActionPerformed(evt);
            }
        });

        jLabel6.setText("Sexo");

        jLabel7.setText("Nacimiento");

        jLabel8.setText("Edad");

        jLabel9.setText("DNI");

        jLabel10.setText("Ciudad");

        jLabel11.setText("Nacionalidad");

        jLabel12.setText("Telefono");

        jLabel13.setText("Elemento antiguo:");

        salidaConsulta.setColumns(20);
        salidaConsulta.setRows(5);
        jScrollPane2.setViewportView(salidaConsulta);

        consulta1.setText("Consulta 1");
        consulta1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                consulta1ActionPerformed(evt);
            }
        });

        consulta2.setText("Consulta 2");
        consulta2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                consulta2ActionPerformed(evt);
            }
        });

        consulta3.setText("Consulta 3");
        consulta3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                consulta3ActionPerformed(evt);
            }
        });

        consulta.setColumns(20);
        consulta.setRows(5);
        jScrollPane3.setViewportView(consulta);

        consulta4.setText("Consulta 4");
        consulta4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                consulta4ActionPerformed(evt);
            }
        });

        consulta5.setText("Consulta 5");
        consulta5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                consulta5ActionPerformed(evt);
            }
        });

        consulta6.setText("Consulta 6");
        consulta6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                consulta6ActionPerformed(evt);
            }
        });

        consulta7.setText("Consulta 7");
        consulta7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                consulta7ActionPerformed(evt);
            }
        });

        ejecutar.setText("Ejecutar consulta");
        ejecutar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ejecutarActionPerformed(evt);
            }
        });

        jButton10.setText("Mostrar XML");
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });

        mensaje1.setText("Consulta:");

        jMenu1.setText("Ficheros XML");

        jMenuItem2.setText("Abrir SAX");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem2);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(mensaje, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 169, Short.MAX_VALUE)
                            .addComponent(mostrarDOM, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addComponent(mostrarSAX)
                        .addGap(18, 18, 18)
                        .addComponent(mostrarJAXB)
                        .addGap(18, 18, 18)
                        .addComponent(botonAñadido1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton10)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(18, 18, 18)
                                .addComponent(newElement, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(24, 24, 24)
                                .addComponent(oldElement))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addComponent(jLabel2)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(apellido1))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addComponent(jLabel1)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(nombre, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel8))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(nacimiento, javax.swing.GroupLayout.DEFAULT_SIZE, 115, Short.MAX_VALUE)
                                    .addComponent(edad)))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(nombrePersona, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(Guardar, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addComponent(jLabel11)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(nacionalidad, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel12)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(telefono, javax.swing.GroupLayout.DEFAULT_SIZE, 95, Short.MAX_VALUE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel3)
                                            .addComponent(jLabel6))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(apellido2, javax.swing.GroupLayout.DEFAULT_SIZE, 87, Short.MAX_VALUE)
                                            .addComponent(sexo))
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel9)
                                            .addComponent(jLabel10))
                                        .addGap(23, 23, 23)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(dni, javax.swing.GroupLayout.DEFAULT_SIZE, 115, Short.MAX_VALUE)
                                            .addComponent(ciudad)))))
                            .addComponent(jScrollPane2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(mensaje1, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(consulta3)
                                .addGap(18, 18, 18)
                                .addComponent(consulta4))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(consulta1)
                                .addGap(18, 18, 18)
                                .addComponent(consulta2))
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(consulta7)
                                .addGap(18, 18, 18)
                                .addComponent(ejecutar))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(consulta5)
                                .addGap(18, 18, 18)
                                .addComponent(consulta6)))
                        .addContainerGap(32, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addComponent(mensaje, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(mostrarDOM)
                    .addComponent(mostrarSAX)
                    .addComponent(mostrarJAXB)
                    .addComponent(botonAñadido1)
                    .addComponent(jButton1)
                    .addComponent(jButton10))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(nombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7)
                            .addComponent(nacimiento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(apellido1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8)
                            .addComponent(edad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(apellido2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9)
                            .addComponent(dni, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(sexo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10)
                            .addComponent(ciudad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel11)
                            .addComponent(nacionalidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel12)
                            .addComponent(telefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Guardar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(nombrePersona, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(newElement, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(5, 5, 5)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel13)
                            .addComponent(oldElement, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(mensaje1)
                        .addGap(4, 4, 4)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(consulta2)
                                    .addComponent(consulta1))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(consulta3)
                                    .addComponent(consulta4))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(consulta6)
                                    .addComponent(consulta5))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(consulta7)
                                    .addComponent(ejecutar))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 10, Short.MAX_VALUE))
                            .addComponent(jScrollPane2))))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mostrarDOMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mostrarDOMActionPerformed
//        File ficheroXML;
//        ficheroXML = dialogoSeleccionarFichero();
//
//        if (ficheroXML == null) {
//            this.mensaje.setText("vuelve a seleccionar el fichero");
//        } else {
//            if (gesDOM.abrir_XML_DOM(ficheroXML) == -1) {
//                this.mensaje.setText("Error al crear el fichero DOM");
//                this.mostrarDOM.setEnabled(false);
//                this.botonAñadido1.setEnabled(false);
//                this.Guardar.setEnabled(false);
//                this.mostrarSAX.setEnabled(false);
//            } else {
//                this.mensaje.setText("¡Objeto DOM creado");
//                this.mostrarDOM.setEnabled(true);
//                this.botonAñadido1.setEnabled(true);
//                this.Guardar.setEnabled(true);
//                this.mostrarSAX.setEnabled(false);
//
//            }
//        }

        //este boton hace que se muestre el dom generado del archivo
        String salida = "";
        salida = gesDOM.recorrerDOMyMostrar();
        this.jTextArea1.setText(salida);

    }//GEN-LAST:event_mostrarDOMActionPerformed

    private void botonAñadido1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonAñadido1ActionPerformed
        //este boton hace que se añada al dom los datos previamente escritos en las cajas de txt 
        if (gesDOM.annadirDOM(this.nombre.getText(), this.apellido1.getText(), this.apellido2.getText(), this.ciudad.getText(),
                this.nacionalidad.getText(), this.sexo.getText(), this.telefono.getText(), this.nacimiento.getText(), this.dni.getText(), this.edad.getText()
        ) == -1) {
            this.mensaje.setText("Error al añadir el nodo");
        } else {
            this.mensaje.setText("Nodo añadido correctamente");
        }
    }//GEN-LAST:event_botonAñadido1ActionPerformed

    private void GuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GuardarActionPerformed
        //este btn hace que se guarde la modificacion en un fichero externo
        if (gesDOM.guardarDOM() == -1) {
            this.mensaje.setText("Error al guardar ");
        } else {
            this.mensaje.setText("DOM guardado con exito");
        }
    }//GEN-LAST:event_GuardarActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try {
            //este btn hace que se ejecute el metodo de la modificacion del titulo
            if (gesJAXB.modificarJAXB(nombrePersona.getText(), newElement.getText(), oldElement.getText()) == false) {
                this.mensaje.setText("Error al modificar el JAXB");
            } else {
                this.mensaje.setText("JAXB modificado correctamente");
            }
        } catch (IOException ex) {
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        
            gesSAX.abrir_XML_SAX(fileXML);
            gesDOM.abrir_XML_DOM(fileXML);
            gesJAXB.abrir_XML_JAXB(fileXML);
// TODO add your handling code here:
//        File ficheroXML;
//        ficheroXML = dialogoSeleccionarFichero();
//
//        if (ficheroXML == null) {
//            this.mensaje.setText("vuelve a seleccionar el fichero");
//        } else {
//            if (gesSAX.abrir_XML_SAX(ficheroXML) == -1) {
//                this.mensaje.setText("Error al crear el fichero SAX");
////                this.mostrarDOM.setEnabled(true);
////                this.botonAñadido1.setEnabled(true);
////                this.Guardar.setEnabled(true);
////                this.mostrarSAX.setEnabled(true);
////                this.jButton1.setEnabled(true);
//
//            } else {
//                this.mensaje.setText("¡Abierto archivo SAX creado");
////                this.mostrarDOM.setEnabled(false);
////                this.botonAñadido1.setEnabled(false);
////                this.Guardar.setEnabled(false);
////                this.jButton1.setEnabled(false);
//            }
//        }
            
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void mostrarSAXActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mostrarSAXActionPerformed
        // TODO add your handling code here:
        String salida = gesSAX.recorrerSAX();
        this.jTextArea1.setText(salida);
    }//GEN-LAST:event_mostrarSAXActionPerformed

    private void mostrarJAXBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mostrarJAXBActionPerformed
        String salida = gesJAXB.recorrerJAXB();
        this.jTextArea1.setText(salida);
    }//GEN-LAST:event_mostrarJAXBActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        // TODO add your handling code here:
        if (gesXpath.abrir_XML(fileXML) == -1) {
            this.mensaje.setText("Error al crear el archivo XML");
            this.ejecutar.setEnabled(false);
        } else {
            this.mensaje.setText("Exito al crear el archivo XMl");
            this.ejecutar.setEnabled(true);
        }
    }//GEN-LAST:event_jButton10ActionPerformed

    private void ejecutarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ejecutarActionPerformed
        // TODO add your handling code here:
        String salida;
        salida = gesXpath.ejecutar__XPath(this.consulta.getText());
        this.salidaConsulta.setText(salida);
    }//GEN-LAST:event_ejecutarActionPerformed

    private void consulta1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_consulta1ActionPerformed
        // TODO add your handling code here:
        this.consulta.setText("/Personas/Persona");
        this.mensaje1.setText("Mostrar todas las personas");
    }//GEN-LAST:event_consulta1ActionPerformed

    private void consulta2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_consulta2ActionPerformed
        // TODO add your handling code here:
        this.consulta.setText("/Personas/Persona/@Edad");
        this.mensaje1.setText("Mostrar todas las edades");
    }//GEN-LAST:event_consulta2ActionPerformed

    private void consulta3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_consulta3ActionPerformed
        // TODO add your handling code here:
        this.consulta.setText("/Personas/Persona[./Ciudad='Sevilla']");
           this.mensaje1.setText("Mostrar todas las personas que su ciudad sea Sevilla");
    }//GEN-LAST:event_consulta3ActionPerformed

    private void consulta4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_consulta4ActionPerformed
        // TODO add your handling code here:
        this.consulta.setText("/Personas/Persona/Nombre"); 
           this.mensaje1.setText("Mostrar todos los nombres");
    }//GEN-LAST:event_consulta4ActionPerformed

    private void consulta5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_consulta5ActionPerformed
        // TODO add your handling code here:
                this.consulta.setText("/Personas/Persona/Ciudad"); 
                   this.mensaje1.setText("Mostrar todas las ciudades");
    }//GEN-LAST:event_consulta5ActionPerformed

    private void consulta6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_consulta6ActionPerformed
        // TODO add your handling code here:
                this.consulta.setText("/Personas/Persona/Nacionalidad"); 
                this.mensaje1.setText("Mostrar todas las nacionalidades");
    }//GEN-LAST:event_consulta6ActionPerformed

    private void consulta7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_consulta7ActionPerformed
        // TODO add your handling code here:
                this.consulta.setText("/Personas/Persona/Sexo"); 
                   this.mensaje1.setText("Mostrar todos los sexos");
    }//GEN-LAST:event_consulta7ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Interfaz().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Guardar;
    private javax.swing.JTextField apellido1;
    private javax.swing.JTextField apellido2;
    private javax.swing.JButton botonAñadido1;
    private javax.swing.JTextField ciudad;
    private javax.swing.JTextArea consulta;
    private javax.swing.JButton consulta1;
    private javax.swing.JButton consulta2;
    private javax.swing.JButton consulta3;
    private javax.swing.JButton consulta4;
    private javax.swing.JButton consulta5;
    private javax.swing.JButton consulta6;
    private javax.swing.JButton consulta7;
    private javax.swing.JTextField dni;
    private javax.swing.JTextField edad;
    private javax.swing.JButton ejecutar;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JLabel mensaje;
    private javax.swing.JLabel mensaje1;
    private javax.swing.JButton mostrarDOM;
    private javax.swing.JButton mostrarJAXB;
    private javax.swing.JButton mostrarSAX;
    private javax.swing.JTextField nacimiento;
    private javax.swing.JTextField nacionalidad;
    private javax.swing.JTextField newElement;
    private javax.swing.JTextField nombre;
    private javax.swing.JTextField nombrePersona;
    private javax.swing.JTextField oldElement;
    private javax.swing.JTextArea salidaConsulta;
    private javax.swing.JTextField sexo;
    private javax.swing.JTextField telefono;
    // End of variables declaration//GEN-END:variables
}
